DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  ID IDENTITY PRIMARY KEY,
  FIRST_NAME VARCHAR(64) NOT NULL,
  LAST_NAME VARCHAR(64) NOT NULL,
  EMAIL VARCHAR(64) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL
);