DROP TABLE IF EXISTS user_account;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS users_roles;

CREATE TABLE user_account (
  ID IDENTITY PRIMARY KEY,
  USER_NAME VARCHAR(64) NOT NULL,
  FIRST_NAME VARCHAR(64) NOT NULL,
  LAST_NAME VARCHAR(64) NOT NULL,
  EMAIL VARCHAR(64) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL
);

CREATE TABLE role (
  id IDENTITY PRIMARY KEY,
  name VARCHAR(64) NOT NULL
);

CREATE TABLE users_roles (
  user_id NUMBER,
  role_id NUMBER
);
