DROP TABLE IF EXISTS user_account;

CREATE TABLE user_account (
  ID IDENTITY PRIMARY KEY,
  FIRST_NAME VARCHAR(64) NOT NULL,
  LAST_NAME VARCHAR(64) NOT NULL,
  EMAIL VARCHAR(64) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL
);
